# Generated by Django 4.0.5 on 2022-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('intro', models.CharField(max_length=250, verbose_name='Intro')),
                ('body', models.TextField(verbose_name='Full_text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
